import { spawn, execFile } from "node:child_process";
import { cp, mkdir, mkdtemp, realpath, rename, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve, sep } from "node:path";
import { promisify } from "node:util";
import { randomUUID } from "node:crypto";
import type { SandboxProvider } from "../../core/sandbox-provider.js";
import type { ExecutionResult, FilesystemChange, ProcessObservation, ResourceLimits, SandboxCommand, SandboxCreateInput, SandboxHandle, SandboxInspection, SandboxSnapshot } from "../../core/sandbox-types.js";
import { SandboxError, sandboxInvariant } from "../../core/sandbox-errors.js";
import { assertSafeRepositorySymlinks, classifyFilesystemChanges, hashFilesystemState, scanFilesystem } from "../../filesystem/observer.js";
const exec = promisify(execFile);
const inside = (root: string, target: string): boolean => target === root || target.startsWith(`${root}${sep}`);
const exists = async (path: string): Promise<boolean> => { try { await stat(path); return true; } catch { return false; } };
const cpuMilliseconds = (value: string): number => { const pieces = value.trim().split(":").map(Number); if (pieces.some(Number.isNaN)) return 0; return pieces.reduce((sum, item) => sum * 60 + item, 0) * 1000; };
const processRows = async (): Promise<{ pid: number; ppid: number; rss: number; cpuMs: number; command: string }[]> => { try { const { stdout } = await exec("ps", ["-axo", "pid=,ppid=,rss=,time=,comm="], { maxBuffer: 2_000_000, encoding: "utf8" }); return stdout.trim().split("\n").map((line) => { const match = line.trim().match(/^(\d+)\s+(\d+)\s+(\d+)\s+(\S+)\s+(.+)$/); return match ? { pid: Number(match[1]), ppid: Number(match[2]), rss: Number(match[3]) * 1024, cpuMs: cpuMilliseconds(match[4]), command: match[5] } : undefined; }).filter((item): item is NonNullable<typeof item> => Boolean(item)); } catch { return []; } };
const descendants = (rows: Awaited<ReturnType<typeof processRows>>, rootPid: number) => { const ids = new Set([rootPid]); let changed = true; while (changed) { changed = false; for (const row of rows) if (ids.has(row.ppid) && !ids.has(row.pid)) { ids.add(row.pid); changed = true; } } return rows.filter((row) => ids.has(row.pid)); };

export class LocalProcessSandboxProvider implements SandboxProvider {
  readonly name = "local-process"; readonly version = "1";
  private macSandboxAvailable?: boolean;
  private async supportsMacSandbox(): Promise<boolean> { if (this.macSandboxAvailable !== undefined) return this.macSandboxAvailable; if (process.platform !== "darwin" || !await exists("/usr/bin/sandbox-exec")) return this.macSandboxAvailable = false; try { await exec("/usr/bin/sandbox-exec", ["-p", "(version 1) (allow default)", "/usr/bin/true"], { timeout: 2_000 }); return this.macSandboxAvailable = true; } catch { return this.macSandboxAvailable = false; } }
  async create(input: SandboxCreateInput): Promise<SandboxHandle> { const root = await realpath(await mkdtemp(join(tmpdir(), `easy-llm-sandbox-${input.sandboxId.slice(-8)}-`))); return { id: input.sandboxId, taskId: input.taskId, projectId: input.projectId, repositoryPath: await realpath(resolve(input.repositoryPath)), workspacePath: join(root, "workspace"), snapshotRoot: join(root, "snapshots"), provider: this.name, policy: input.policy, limits: input.limits }; }
  async prepare(handle: SandboxHandle): Promise<void> { await assertSafeRepositorySymlinks(handle.repositoryPath); await cp(handle.repositoryPath, handle.workspacePath, { recursive: true, preserveTimestamps: true, verbatimSymlinks: true, errorOnExist: true }); await mkdir(handle.snapshotRoot, { recursive: true }); await mkdir(join(handle.workspacePath, ".easy-llm-sandbox", "tmp"), { recursive: true }); }
  async execute(handle: SandboxHandle, command: SandboxCommand): Promise<ExecutionResult> {
    sandboxInvariant(await exists(handle.workspacePath), "SANDBOX_WORKSPACE_MISSING", handle.workspacePath); const cwd = resolve(handle.workspacePath, command.cwd ?? "."); sandboxInvariant(inside(handle.workspacePath, cwd), "SANDBOX_PATH_ESCAPE", command.cwd ?? "");
    const limits: ResourceLimits = { ...handle.limits, ...command.limits }, before = await scanFilesystem(handle.workspacePath), started = Date.now(), startedAt = new Date().toISOString(), observations = new Map<number, ProcessObservation>();
    const profile = ["(version 1)", "(allow default)", "(deny file-write*)", `(allow file-write* (subpath ${JSON.stringify(handle.workspacePath)}) (literal \"/dev/null\"))`, handle.policy.network.mode === "none" ? "(deny network*)" : ""].filter(Boolean).join("\n");
    const useMacSandbox = await this.supportsMacSandbox(), executable = useMacSandbox ? "/usr/bin/sandbox-exec" : command.executable, args = useMacSandbox ? ["-p", profile, command.executable, ...command.args] : command.args;
    const environment: NodeJS.ProcessEnv = { PATH: process.env.PATH, CI: "1", NO_COLOR: "1", HOME: join(handle.workspacePath, ".easy-llm-sandbox"), TMPDIR: join(handle.workspacePath, ".easy-llm-sandbox", "tmp"), npm_config_cache: join(handle.workspacePath, ".easy-llm-sandbox", "npm-cache"), ...command.environment };
    if (handle.policy.network.mode !== "full") { environment.HTTP_PROXY = "http://127.0.0.1:9"; environment.HTTPS_PROXY = "http://127.0.0.1:9"; environment.NO_PROXY = handle.policy.network.mode === "allowlist" ? handle.policy.network.hosts.join(",") : ""; environment.npm_config_offline = "true"; }
    let stdout = "", stderr = "", exceeded: string | undefined, timedOut = false, peakMemoryBytes = 0, cpuMs = 0, maxProcesses = 1, done = false, signal: string | undefined;
    const child = spawn(executable, args, { cwd, env: environment, detached: process.platform !== "win32", stdio: [command.stdin ? "pipe" : "ignore", "pipe", "pipe"] });
    observations.set(child.pid ?? -1, { id: `process:${handle.id}:${child.pid}`, sandboxId: handle.id, taskId: handle.taskId, pid: child.pid ?? -1, parentPid: process.pid, executable: command.executable, args: command.args, startedAt });
    const terminate = () => { if (!child.pid) return; signal = "SIGKILL"; try { if (process.platform !== "win32") process.kill(-child.pid, "SIGKILL"); else child.kill("SIGKILL"); } catch { child.kill("SIGKILL"); } };
    const append = (target: "stdout" | "stderr", bytes: Buffer) => { const text = bytes.toString("utf8"); if (target === "stdout") stdout += text; else stderr += text; if (Buffer.byteLength(stdout) + Buffer.byteLength(stderr) > limits.maxOutputBytes && !exceeded) { exceeded = "output"; terminate(); } };
    child.stdout?.on("data", (bytes: Buffer) => append("stdout", bytes)); child.stderr?.on("data", (bytes: Buffer) => append("stderr", bytes)); if (command.stdin && child.stdin) { child.stdin.end(command.stdin); }
    const monitor = setInterval(async () => { if (done || !child.pid) return; const tree = descendants(await processRows(), child.pid); maxProcesses = Math.max(maxProcesses, tree.length); peakMemoryBytes = Math.max(peakMemoryBytes, tree.reduce((sum, item) => sum + item.rss, 0)); cpuMs = Math.max(cpuMs, tree.reduce((sum, item) => sum + item.cpuMs, 0)); for (const row of tree) if (!observations.has(row.pid)) observations.set(row.pid, { id: `process:${handle.id}:${row.pid}`, sandboxId: handle.id, taskId: handle.taskId, pid: row.pid, parentPid: row.ppid, executable: row.command, args: [], startedAt: new Date().toISOString() }); if (!exceeded && tree.length > limits.maxProcesses) { exceeded = "process_count"; terminate(); } else if (!exceeded && peakMemoryBytes > limits.maxMemoryBytes) { exceeded = "memory"; terminate(); } else if (!exceeded && cpuMs > limits.maxCpuMs) { exceeded = "cpu"; terminate(); } }, 50);
    const timeout = setTimeout(() => { timedOut = true; terminate(); }, Math.min(command.timeoutMs ?? limits.maxWallTimeMs, limits.maxWallTimeMs));
    const completion = await new Promise<{ code?: number; signal?: string; error?: Error }>((resolveResult) => { child.once("error", (error) => resolveResult({ error })); child.once("close", (code, closeSignal) => resolveResult({ code: code ?? undefined, signal: closeSignal ?? undefined })); }); done = true; clearInterval(monitor); clearTimeout(timeout);
    const durationMs = Date.now() - started, exitedAt = new Date().toISOString(); for (const observation of observations.values()) { observation.exitedAt = exitedAt; observation.durationMs = durationMs; if (observation.pid === child.pid) { observation.exitCode = completion.code; observation.signal = completion.signal ?? signal; } }
    const after = await scanFilesystem(handle.workspacePath), filesystemChanges = classifyFilesystemChanges(before, after, { sandboxId: handle.id, taskId: handle.taskId });
    if (filesystemChanges.length > limits.maxFilesystemChanges && !exceeded) exceeded = "filesystem_changes";
    const outputBytes = Math.min(limits.maxOutputBytes, Buffer.byteLength(stdout) + Buffer.byteLength(stderr)), status = timedOut ? "timed_out" : exceeded ? "resource_exceeded" : completion.error || completion.code !== 0 ? "failed" : "completed";
    return { id: `command:${handle.id}:${randomUUID()}`, sandboxId: handle.id, taskId: handle.taskId, command, exitCode: completion.code, signal: completion.signal ?? signal, stdout: stdout.slice(0, limits.maxOutputBytes), stderr: `${stderr}${completion.error?.message ?? ""}`.slice(0, limits.maxOutputBytes), durationMs, status, failureReason: timedOut ? "process_timeout" : exceeded ? `resource_limit:${exceeded}` : completion.error ? "missing_tool" : completion.code ? "command_failure" : undefined,
      resourceUsage: { durationMs, cpuMs, peakMemoryBytes, processCount: maxProcesses, filesystemChangeCount: filesystemChanges.length, outputBytes, networkEventCount: 0 }, processes: [...observations.values()].sort((a, b) => a.pid - b.pid), filesystemChanges, network: [] };
  }
  async snapshot(handle: SandboxHandle, input: { id: string; label: string; environmentFingerprint: string; origin: import("../../core/sandbox-types.js").WorkspaceOrigin; policy: import("../../core/sandbox-types.js").SandboxPolicy; limits: ResourceLimits }): Promise<SandboxSnapshot> { const path = join(handle.snapshotRoot, input.id.replace(/[^a-zA-Z0-9_.-]/g, "_")); await cp(handle.workspacePath, path, { recursive: true, preserveTimestamps: true, verbatimSymlinks: true, errorOnExist: true }); return { id: input.id, sandboxId: handle.id, taskId: handle.taskId, label: input.label, createdAt: new Date().toISOString(), workspaceHash: hashFilesystemState(await scanFilesystem(handle.workspacePath)), environmentFingerprint: input.environmentFingerprint, origin: input.origin, policy: input.policy, limits: input.limits, providerData: { path } }; }
  async restore(handle: SandboxHandle, snapshot: SandboxSnapshot): Promise<void> { if (snapshot.sandboxId !== handle.id || snapshot.taskId !== handle.taskId) throw new SandboxError("SANDBOX_SNAPSHOT_SCOPE", snapshot.id); const source = snapshot.providerData.path; if (typeof source !== "string" || !await exists(source)) throw new SandboxError("SANDBOX_SNAPSHOT_MISSING", snapshot.id); const replacement = `${handle.workspacePath}.restore-${randomUUID()}`, backup = `${handle.workspacePath}.backup-${randomUUID()}`; try { await cp(source, replacement, { recursive: true, preserveTimestamps: true, verbatimSymlinks: true, errorOnExist: true }); await rename(handle.workspacePath, backup); await rename(replacement, handle.workspacePath); await rm(backup, { recursive: true, force: true }); } catch (error) { if (await exists(backup) && !await exists(handle.workspacePath)) await rename(backup, handle.workspacePath); await rm(replacement, { recursive: true, force: true }); throw error; } }
  async destroy(handle: SandboxHandle): Promise<void> { const root = dirname(handle.workspacePath); if (!basename(root).startsWith("easy-llm-sandbox-")) throw new SandboxError("SANDBOX_DESTROY_SCOPE", root); await rm(root, { recursive: true, force: true }); }
  async inspect(handle: SandboxHandle): Promise<SandboxInspection> { const workspaceExists = await exists(handle.workspacePath); return { sandbox: undefined as never, exists: workspaceExists, recoverable: workspaceExists, processes: [], filesystemChanges: [] }; }
}
