import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { discoverProject } from "../src/discovery/discover-project.js";
import { createFeltDBProjectMemory } from "../src/memory/feltdb-project-memory.js";
import { SandboxManager } from "../src/sandbox/core/sandbox-manager.js";
import { LocalProcessSandboxProvider } from "../src/sandbox/providers/local/local-process-provider.js";
import { createEnvironmentFingerprint } from "../src/sandbox/environment/fingerprint.js";
import { detectSandboxEnvironment } from "../src/sandbox/environment/detector.js";

const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map((path) => rm(path, { recursive: true, force: true }))); });
const fixture = async () => { const root = await mkdtemp(join(tmpdir(), "pr10-fixture-")); roots.push(root); await writeFile(join(root, "package.json"), JSON.stringify({ name: "pr10", scripts: { mutate: "node -e \"require('fs').writeFileSync('result.txt','sandbox')\"", test: "node -e \"process.exit(0)\"" } })); await writeFile(join(root, "source.txt"), "canonical"); const project = await discoverProject(root), memory = createFeltDBProjectMemory({ root, ephemeral: true }); await memory.initialize(project); return { root, project, memory }; };
const running = async () => { const setup = await fixture(), manager = new SandboxManager({ memory: setup.memory, provider: new LocalProcessSandboxProvider() }); let sandbox = await manager.create({ taskId: `task-${Date.now()}-${Math.random()}`, projectId: setup.project.id, repositoryPath: setup.root }); sandbox = await manager.prepare(sandbox.id, { languages: setup.project.detectedLanguages }); sandbox = await manager.start(sandbox.id); return { ...setup, manager, sandbox }; };

describe("PR10 isolated execution substrate certification", () => {
  it("executes mutations only in the copied workspace and restores snapshots", async () => { const { root, manager, sandbox } = await running(); const snapshot = await manager.snapshot(sandbox.id, "before command"), result = await manager.execute(sandbox.id, { executable: "npm", args: ["run", "mutate"] }); expect(result.status).toBe("completed"); expect(await readFile(join(root, "source.txt"), "utf8")).toBe("canonical"); expect(await readFile(join(await manager.workspacePath(sandbox.id), "result.txt"), "utf8")).toBe("sandbox"); await manager.restore(sandbox.id, snapshot.id); await expect(readFile(join(await manager.workspacePath(sandbox.id), "result.txt"), "utf8")).rejects.toThrow(); await manager.destroy(sandbox.id); });

  it("blocks untrusted commands, network requests, and path traversal deterministically", async () => { const { manager, sandbox } = await running(); const blocked = await manager.execute(sandbox.id, { executable: "sh", args: ["-c", "true"] }), network = await manager.execute(sandbox.id, { executable: "npm", args: ["test"], networkHosts: ["example.com"] }); expect(blocked.status).toBe("blocked"); expect(network).toMatchObject({ status: "blocked", failureReason: "network_blocked" }); await expect(manager.execute(sandbox.id, { executable: "npm", args: ["test"], cwd: "../../" })).rejects.toThrow("SANDBOX_PATH_ESCAPE"); const repeat = await manager.execute(sandbox.id, { executable: "sh", args: ["-c", "true"] }); expect(repeat.stderr).toBe(blocked.stderr); await manager.destroy(sandbox.id); });

  it("rejects repository symlinks that escape the project", async () => { const setup = await fixture(), outside = await mkdtemp(join(tmpdir(), "pr10-outside-")); roots.push(outside); await writeFile(join(outside, "secret"), "secret"); await symlink(join(outside, "secret"), join(setup.root, "escape")); const manager = new SandboxManager({ memory: setup.memory, provider: new LocalProcessSandboxProvider() }), sandbox = await manager.create({ taskId: "symlink-task", projectId: setup.project.id, repositoryPath: setup.root }); await expect(manager.prepare(sandbox.id)).rejects.toThrow("SANDBOX_SYMLINK_ESCAPE"); await manager.destroy(sandbox.id); });

  it("persists ordered command, process, filesystem, network, snapshot, and lifecycle evidence", async () => { const { memory, manager, sandbox } = await running(); await manager.execute(sandbox.id, { executable: "npm", args: ["run", "mutate"] }); const inspection = await manager.inspect(sandbox.id); expect(inspection.commands).toHaveLength(1); expect(inspection.processes.length).toBeGreaterThan(0); expect(inspection.filesystemChanges.some((item) => item.path === "result.txt")).toBe(true); expect(inspection.snapshots.length).toBeGreaterThan(0); expect(inspection.events.map((item) => item.sequence)).toEqual(inspection.events.map((_, index) => index)); expect(inspection.events.some((item) => item.type === "process.started")).toBe(true); expect((await memory.listRelationships()).some((edge) => edge.relation === "EXECUTED_IN")).toBe(true); await manager.destroy(sandbox.id); });

  it("resumes a retained sandbox through a new provider instance", async () => { const { memory, manager, sandbox } = await running(); await manager.pause(sandbox.id); const replacement = new SandboxManager({ memory, provider: new LocalProcessSandboxProvider() }), resumed = await replacement.resume(sandbox.id); expect(resumed.status).toBe("running"); expect(await replacement.workspacePath(sandbox.id)).toBe(sandbox.workspace.path); await replacement.destroy(sandbox.id); });

  it("produces stable environment fingerprints and changes them with dependency state", async () => { const { root } = await fixture(), environment = await detectSandboxEnvironment(root), input = { workspace: root, environment, provider: "local-process", providerVersion: "1", networkPolicy: { mode: "none" as const, hosts: [] }, limits: { maxCpuMs: 1, maxMemoryBytes: 1, maxWallTimeMs: 1, maxOutputBytes: 1, maxProcesses: 1, maxFilesystemChanges: 1 } }; const first = await createEnvironmentFingerprint(input), second = await createEnvironmentFingerprint(input); expect(second.fingerprint).toBe(first.fingerprint); await writeFile(join(root, "package.json"), JSON.stringify({ name: "changed" })); expect((await createEnvironmentFingerprint(input)).fingerprint).not.toBe(first.fingerprint); });
});
