import { afterEach, describe, expect, it } from "vitest";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { RuntimeClient, type IDECapabilities, type TaskCreateInput } from "@easy-llm/code-ide";
import { discoverProject } from "../src/discovery/discover-project.js";
import { createFeltDBProjectMemory } from "../src/memory/feltdb-project-memory.js";
import { indexProjectIntoMemory } from "../src/indexing/index-project.js";
import { startRuntimeServer } from "../src/ide/runtime-server.js";
import { createIDERegistry } from "../src/ide/registry.js";
import { ideCapabilities } from "../src/ide/capabilities.js";
import { resolveIDESelection, writeIDEConfiguration } from "../src/ide/config.js";

const roots: string[] = [], servers: { close(): Promise<void> }[] = [];
const exec = promisify(execFile);
afterEach(async () => { await Promise.all(servers.splice(0).map((server) => server.close().catch(() => undefined))); await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true }))); });
const fixture = async () => { const root = await mkdtemp(join(tmpdir(), "pr11-fixture-")); roots.push(root); await writeFile(join(root, "package.json"), JSON.stringify({ name: "pr11", scripts: { test: "node verify.cjs" } })); await writeFile(join(root, "value.ts"), "export const value = 1;\n"); await writeFile(join(root, "verify.cjs"), "process.exit(require('fs').readFileSync('value.ts','utf8').includes('2') ? 0 : 1)"); await exec("git", ["-C", root, "init"]); await exec("git", ["-C", root, "config", "user.email", "test@example.com"]); await exec("git", ["-C", root, "config", "user.name", "Test"]); await exec("git", ["-C", root, "add", "."]); await exec("git", ["-C", root, "commit", "-m", "fixture"]); const project = await discoverProject(root), memory = createFeltDBProjectMemory({ root, ephemeral: true }); await memory.initialize(project); await indexProjectIntoMemory(root, project, memory); return { root, project, memory }; };
const capabilities: IDECapabilities = ideCapabilities({ openFile: true, tasks: true, progress: true });
const waitFor = async <T>(read: () => Promise<T>, accept: (value: T) => boolean, timeout = 5_000): Promise<T> => { const started = Date.now(); while (true) { const value = await read(); if (accept(value)) return value; if (typeof value === "object" && value && "state" in value && value.state === "failed") throw new Error(`TASK_FAILED: ${JSON.stringify(value)}`); if (Date.now() - started > timeout) throw new Error("WAIT_TIMEOUT"); await new Promise((resolve) => setTimeout(resolve, 20)); } };
const patch = "--- a/value.ts\n+++ b/value.ts\n@@ -1,1 +1,1 @@\n-export const value = 1;\n+export const value = 2;";

describe("PR11 IDE protocol and adapter certification", () => {
  it("negotiates capabilities, creates an IDE task, streams ordered events, approves, and projects diff/sandbox state", async () => { const setup = await fixture(), runtime = await startRuntimeServer({ ...setup, runnerOptions: { plannerLlm: async () => ({ id: "plan", taskId: "assigned", objective: "change value", assumptions: [], steps: [{ id: "step", order: 1, action: "inspect", description: "inspect value", target: "value.ts", dependencies: [], evidence: ["file:value.ts"] }], risks: [], expectedFiles: ["value.ts"], verification: [{ id: "verify", description: "test", evidence: ["file:value.ts"] }] }), mutationLlm: async ({ plan }) => ({ id: "proposal", taskId: plan.taskId, planId: plan.id, files: [{ path: "value.ts", operation: "modify", patch }], rationale: "test", expectedChanges: ["value"], verification: [{ id: "test", command: "npm test", purpose: "test", required: true, timeoutMs: 5_000 }] }) } }); servers.push(runtime); const client = new RuntimeClient({ baseUrl: runtime.url, token: runtime.token, pollIntervalMs: 10 }), connection = await client.connect({ identity: { id: "test-ide", name: "Test IDE", adapterVersion: "1" }, capabilities }); expect(connection.capabilities.progress).toBe(true); expect(await client.indexProject()).toMatchObject({ files: 3, commits: 1 }); const received: string[] = [], unsubscribe = client.subscribeToEvents((event) => received.push(`${event.sequence}:${event.type}`)); const input: TaskCreateInput = { request: "Change the value", workspace: runtime.workspace, mode: "edit", ide: { id: "test-ide", adapterVersion: "1", capabilities } }, task = await client.createTask(input); const pending = await waitFor(() => client.getTask(task.id), (value) => Boolean(value.approval)); expect(pending.approval?.files).toEqual(["value.ts"]); await client.approveTask(task.id, "approve"); const completed = await waitFor(() => client.getTask(task.id), (value) => value.state === "completed"); expect(completed.state).toBe("completed"); expect(await readFile(join(setup.root, "value.ts"), "utf8")).toContain("2"); const diff = await client.getDiff(task.id), sandbox = await client.getSandbox(task.id); expect(diff).toMatchObject({ additions: 1, deletions: 1 }); expect((sandbox.sandbox as { taskId: string }).taskId).toBe(task.id); await waitFor(async () => received, (events) => events.some((event) => event.endsWith(":task.completed"))); const sequences = received.map((item) => Number(item.split(":")[0])); expect(sequences).toEqual([...new Set(sequences)].sort((a, b) => a - b)); unsubscribe(); await client.disconnect(); }, 15_000);

  it("replays events without duplicates after a cursor and rejects invalid credentials", async () => { const setup = await fixture(), runtime = await startRuntimeServer({ ...setup, runnerOptions: { askLlm: async () => ({ answer: 42 }) } }); servers.push(runtime); const client = new RuntimeClient({ baseUrl: runtime.url, token: runtime.token, pollIntervalMs: 10 }); await client.connect({ identity: { id: "test", name: "Test", adapterVersion: "1" }, capabilities }); const events: string[] = [], unsubscribe = client.subscribeToEvents((event) => events.push(event.id)); const task = await client.createTask({ request: "Explain value", workspace: runtime.workspace, mode: "ask" }); await waitFor(() => client.getTask(task.id), (value) => value.state === "completed"); await waitFor(async () => events, (value) => value.length > 3); expect(new Set(events).size).toBe(events.length); const unauthorized = new RuntimeClient({ baseUrl: runtime.url, token: "wrong" }); await expect(unauthorized.getCapabilities()).rejects.toThrow("RUNTIME_401"); unsubscribe(); await client.disconnect(); });

  it("pauses, resumes, and terminally cancels through runtime-owned task control", async () => {
    const setup = await fixture(), runtime = await startRuntimeServer({ ...setup, runnerOptions: {
      plannerLlm: async () => ({ id: "control-plan", taskId: "assigned", objective: "change value", assumptions: [], steps: [{ id: "inspect", order: 1, action: "inspect", description: "inspect value", target: "value.ts", dependencies: [], evidence: ["file:value.ts"] }], risks: [], expectedFiles: ["value.ts"], verification: [] }),
      mutationLlm: async ({ plan }) => ({ id: "control-proposal", taskId: plan.taskId, planId: plan.id, files: [{ path: "value.ts", operation: "modify", patch }], rationale: "test", expectedChanges: ["value"], verification: [] })
    } }); servers.push(runtime); const client = new RuntimeClient({ baseUrl: runtime.url, token: runtime.token }); await client.connect({ identity: { id: "test", name: "Test", adapterVersion: "1" }, capabilities }); const task = await client.createTask({ request: "Control value", workspace: runtime.workspace, mode: "edit" }); await waitFor(() => client.getTask(task.id), (value) => Boolean(value.approval)); await client.pauseTask(task.id); await waitFor(() => client.getTask(task.id), (value) => value.state === "paused"); await client.resumeTask(task.id); await waitFor(() => client.getTask(task.id), (value) => Boolean(value.approval)); await client.cancelTask(task.id); const cancelled = await waitFor(() => client.getTask(task.id), (value) => value.state === "cancelled"); expect(cancelled.state).toBe("cancelled"); expect(await readFile(join(setup.root, "value.ts"), "utf8")).toContain("1"); await client.disconnect();
  }, 15_000);

  it("enforces repository association and prevents cross-workspace task creation", async () => { const setup = await fixture(), other = await fixture(), runtime = await startRuntimeServer({ ...setup, runnerOptions: { askLlm: async () => "ok" } }); servers.push(runtime); const client = new RuntimeClient({ baseUrl: runtime.url, token: runtime.token }); await client.connect({ identity: { id: "test", name: "Test", adapterVersion: "1" }, capabilities }); await expect(client.createTask({ request: "escape", mode: "ask", workspace: { ...runtime.workspace, workspacePath: other.root, repositoryRoot: other.root } })).rejects.toThrow("RUNTIME_403"); await client.disconnect(); });

  it("keeps adapter metadata separate from runtime logic and handles unsupported capabilities", async () => { const registry = createIDERegistry(), adapters = registry.list(); expect(adapters.map((adapter) => adapter.id)).toEqual(["cursor", "vscode", "zed"]); for (const adapter of adapters) { expect(Object.keys(adapter.capabilities)).toHaveLength(16); await expect(adapter.applyWorkspaceChanges({ workspace: { workspacePath: "/tmp", workspaceId: "x", repositoryRoot: "/tmp" }, diff: { taskId: "x", files: [], additions: 0, deletions: 0 } })).rejects.toThrow("IDE_CAPABILITY_UNSUPPORTED"); } });

  it("resolves explicit, user, project, then detected IDE configuration without project memory", async () => { const root = await mkdtemp(join(tmpdir(), "pr11-config-")); roots.push(root); const user = join(root, "user.json"); await writeIDEConfiguration({ selectedIDE: "cursor" }, user); await writeFile(join(root, ".easy-llm-code.json"), JSON.stringify({ preferredIDE: "vscode" })); expect(await resolveIDESelection({ explicit: "vscode", userConfigPath: user, projectRoot: root, detected: ["cursor"] })).toMatchObject({ id: "vscode", source: "explicit" }); expect(await resolveIDESelection({ userConfigPath: user, projectRoot: root, detected: ["vscode"] })).toMatchObject({ id: "cursor", source: "user" }); await writeIDEConfiguration({}, user); expect(await resolveIDESelection({ userConfigPath: user, projectRoot: root, detected: ["cursor"] })).toMatchObject({ id: "vscode", source: "project" }); });
});
