import * as vscode from "vscode";
import { relative } from "node:path";
import type { IDEProtocolEvent, TaskCreateInput } from "@easy-llm/code-ide";
import type { ExtensionRuntime, RuntimeSnapshot } from "./runtime.js";

export class SidebarProvider implements vscode.WebviewViewProvider, vscode.Disposable {
  private view?: vscode.WebviewView; private disposables: vscode.Disposable[] = [];
  constructor(private readonly extensionUri: vscode.Uri, private readonly runtime: ExtensionRuntime, private readonly output: vscode.OutputChannel, private readonly start: () => Promise<void>) {}
  async resolveWebviewView(view: vscode.WebviewView): Promise<void> { this.view = view; view.webview.options = { enableScripts: true, localResourceRoots: [vscode.Uri.joinPath(this.extensionUri, "media")] }; view.webview.html = html(view.webview, this.extensionUri); this.disposables.push(view.webview.onDidReceiveMessage((message) => this.receive(message)), view.onDidDispose(() => { this.view = undefined; })); try { await this.start(); } catch (error) { this.fail(error); } }
  publishSnapshot(snapshot: RuntimeSnapshot): void { void this.view?.webview.postMessage({ type: "snapshot", snapshot }); }
  publishEvent(event: IDEProtocolEvent): void { void this.view?.webview.postMessage({ type: "event", event }); }
  async refresh(): Promise<void> { await this.runtime.refresh(); }
  async restart(): Promise<void> { try { await this.start(); } catch (error) { this.fail(error); } }
  private async receive(message: { type?: string; request?: string; mode?: TaskCreateInput["mode"]; taskId?: string }): Promise<void> { try { if (message.type === "ready") this.publishSnapshot(this.runtime.current()); else if (message.type === "submit" && message.request?.trim()) await this.runtime.createTask(message.request.trim(), message.mode ?? "auto", editorContext()); else if (message.type === "refresh") await this.refresh(); else if (message.type === "setup") await vscode.commands.executeCommand("easyLlmCode.setupProvider"); else if (message.type === "unlock") await vscode.commands.executeCommand("easyLlmCode.unlockProvider"); else if (message.type === "approve" && message.taskId) await this.runtime.approve(message.taskId, true); else if (message.type === "reject" && message.taskId) await this.runtime.approve(message.taskId, false); else if (message.type === "diff" && message.taskId) { const diff = await this.runtime.getDiff(message.taskId); const document = await vscode.workspace.openTextDocument({ content: diff.files.flatMap((file) => file.hunks.flatMap((hunk) => [`--- ${file.path}`, hunk.header, ...hunk.lines])).join("\n"), language: "diff" }); await vscode.window.showTextDocument(document); } } catch (error) { this.fail(error); } }
  private fail(error: unknown): void { const message = error instanceof Error ? error.message : String(error); this.output.appendLine(message); void this.view?.webview.postMessage({ type: "error", message }); void vscode.window.showErrorMessage(`easy-llm-code: ${message}`); }
  dispose(): void { void this.runtime.stop(); for (const item of this.disposables) item.dispose(); }
}

const html = (webview: vscode.Webview, extensionUri: vscode.Uri): string => { const nonce = Math.random().toString(36).slice(2), style = webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, "media", "sidebar.css")), script = webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, "media", "sidebar.js")); return `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${style}"></head><body><header><div><strong>easy-llm-code</strong><span id="status">Starting…</span></div><button id="refresh" title="Refresh">↻</button></header><section id="provider" hidden><p>Connect an LLM provider to start coding.</p><div><button id="setup">Set up provider</button><button id="unlock">Unlock vault</button></div></section><main id="messages"><div class="empty">Ask about the code or request a change.</div></main><section id="approval" hidden></section><footer><select id="mode" aria-label="Task mode"><option value="auto">Auto</option><option value="ask">Ask</option><option value="plan">Plan</option><option value="edit">Edit</option></select><textarea id="prompt" rows="3" placeholder="Ask anything…"></textarea><button id="send" aria-label="Send">↑</button></footer><script nonce="${nonce}" src="${script}"></script></body></html>`; };

const editorContext = (): { activeFile?: string; selection?: { startLine: number; startColumn: number; endLine: number; endColumn: number; text?: string }; cursor?: { line: number; column: number }; openFiles?: string[] } => { const folder = vscode.workspace.workspaceFolders?.[0], editor = vscode.window.activeTextEditor; if (!folder || !editor) return {}; const activeFile = relative(folder.uri.fsPath, editor.document.uri.fsPath).replaceAll("\\", "/"), selection = editor.selection; return { activeFile, cursor: { line: selection.active.line + 1, column: selection.active.character + 1 }, ...(!selection.isEmpty ? { selection: { startLine: selection.start.line + 1, startColumn: selection.start.character + 1, endLine: selection.end.line + 1, endColumn: selection.end.character + 1, text: editor.document.getText(selection) } } : {}), openFiles: vscode.window.visibleTextEditors.map((item) => relative(folder.uri.fsPath, item.document.uri.fsPath).replaceAll("\\", "/")) }; };
