import * as vscode from "vscode";
import { relative } from "node:path";
import type { IDEProtocolEvent, TaskCreateInput } from "@easy-llm/code-ide";
import type { ExtensionRuntime, RuntimeSnapshot } from "./runtime.js";

export class SidebarProvider implements vscode.WebviewViewProvider, vscode.Disposable {
  private view?: vscode.WebviewView; private disposables: vscode.Disposable[] = [];
  constructor(private readonly extensionUri: vscode.Uri, private readonly runtime: ExtensionRuntime, private readonly output: vscode.OutputChannel, private readonly start: () => Promise<void>) {}
  async resolveWebviewView(view: vscode.WebviewView): Promise<void> { this.view = view; view.webview.options = { enableScripts: true, localResourceRoots: [vscode.Uri.joinPath(this.extensionUri, "media")] }; view.webview.html = html(view.webview, this.extensionUri); this.disposables.push(view.webview.onDidReceiveMessage((message) => this.receive(message)), view.onDidDispose(() => { this.view = undefined; })); try { await this.start(); } catch (error) { this.fail(error); } }
  publishSnapshot(snapshot: RuntimeSnapshot): void { void this.view?.webview.postMessage({ type: "snapshot", snapshot }); }
  publishEvent(event: IDEProtocolEvent): void { void this.view?.webview.postMessage({ type: "event", event }); }
  async refresh(): Promise<void> { await this.runtime.refresh(); }
  async restart(): Promise<void> { try { await this.start(); } catch (error) { this.fail(error); } }
  private async receive(message: { type?: string; request?: string; mode?: TaskCreateInput["mode"]; model?: string; taskId?: string }): Promise<void> { try { if (message.type === "ready") this.publishSnapshot(this.runtime.current()); else if (message.type === "submit" && message.request?.trim()) await this.runtime.createTask(message.request.trim(), message.mode ?? "auto", message.model ?? "auto", editorContext(this.runtime.workspaceRoot())); else if (message.type === "index") { const result = await this.runtime.indexProject(); void this.view?.webview.postMessage({ type: "notice", message: `Indexed ${result.files} files${result.commits ? ` and ${result.commits} new commits` : ""}.` }); } else if (message.type === "newSession") this.runtime.newSession(); else if (message.type === "refresh") await this.refresh(); else if (message.type === "setup") await vscode.commands.executeCommand("easyLlmCode.setupProvider"); else if (message.type === "unlock") await vscode.commands.executeCommand("easyLlmCode.unlockProvider"); else if (message.type === "approve" && message.taskId) await this.runtime.approve(message.taskId, true); else if (message.type === "reject" && message.taskId) await this.runtime.approve(message.taskId, false); else if (message.type === "diff" && message.taskId) { const diff = await this.runtime.getDiff(message.taskId); const document = await vscode.workspace.openTextDocument({ content: diff.files.flatMap((file) => file.hunks.flatMap((hunk) => [`--- ${file.path}`, hunk.header, ...hunk.lines])).join("\n"), language: "diff" }); await vscode.window.showTextDocument(document); } } catch (error) { this.fail(error); } }
  private fail(error: unknown): void { const message = error instanceof Error ? error.message : String(error); this.output.appendLine(message); void this.view?.webview.postMessage({ type: "error", message }); void vscode.window.showErrorMessage(`easy-llm-code: ${message}`); }
  dispose(): void { void this.runtime.stop(); for (const item of this.disposables) item.dispose(); }
}

const html = (webview: vscode.Webview, extensionUri: vscode.Uri): string => { const nonce = Math.random().toString(36).slice(2), style = webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, "media", "sidebar.css")), script = webview.asWebviewUri(vscode.Uri.joinPath(extensionUri, "media", "sidebar.js")); return `<!doctype html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource}; script-src 'nonce-${nonce}';"><link rel="stylesheet" href="${style}"></head><body><nav><button class="tab active" data-view="chat">CHAT</button><button class="tab" data-view="history">HISTORY</button><span></span><button id="newSession" title="New chat" aria-label="New chat">＋</button></nav><header><div class="brand"><span class="mark">›_</span><div><strong>easy-llm-code</strong><span id="status">Starting runtime…</span></div></div><button id="refresh" title="Refresh" aria-label="Refresh">↻</button></header><section id="provider" hidden><span class="provider-icon">◇</span><div class="provider-copy"><strong>Connect a model</strong><p>Set up a provider or unlock your encrypted vault to begin.</p><div class="provider-actions"><button id="setup">Set up</button><button id="unlock" class="secondary">Unlock vault</button></div></div></section><main id="messages"><div class="empty"><span class="empty-mark">›_</span><strong>Ready when you are</strong><p>Ask about this project or describe a change.</p></div></main><section id="approval" hidden></section><footer><textarea id="prompt" rows="3" placeholder="Ask anything…"></textarea><div class="composer-actions"><select id="mode" aria-label="Task mode"><option value="auto">Auto</option><option value="ask">Ask</option><option value="plan">Plan</option><option value="edit">Edit</option></select><select id="model" aria-label="Model"><option value="auto">Auto model</option></select><span class="context-hint">Current file</span><button id="send" aria-label="Send">↑</button></div></footer><script nonce="${nonce}" src="${script}"></script></body></html>`; };

const editorContext = (root: string): { activeFile?: string; selection?: { startLine: number; startColumn: number; endLine: number; endColumn: number; text?: string }; cursor?: { line: number; column: number }; openFiles?: string[] } => { const editor = vscode.window.activeTextEditor; if (!root || !editor) return {}; const activeFile = relative(root, editor.document.uri.fsPath).replaceAll("\\", "/"); if (activeFile.startsWith("../") || activeFile === "..") return {}; const selection = editor.selection, openFiles = vscode.window.visibleTextEditors.map((item) => relative(root, item.document.uri.fsPath).replaceAll("\\", "/")).filter((item) => item !== ".." && !item.startsWith("../")); return { activeFile, cursor: { line: selection.active.line + 1, column: selection.active.character + 1 }, ...(!selection.isEmpty ? { selection: { startLine: selection.start.line + 1, startColumn: selection.start.character + 1, endLine: selection.end.line + 1, endColumn: selection.end.character + 1, text: editor.document.getText(selection) } } : {}), openFiles }; };
