import { chmod, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { randomUUID } from "node:crypto";
export interface IDEConfiguration { selectedIDE?: string; adapterConfiguration?: Record<string, Record<string, unknown>>; transport?: "stdio" | "http" | "websocket" | "unix" }
const defaultPath = () => process.env.EASY_LLM_CODE_IDE_CONFIG ?? join(homedir(), ".config", "easy-llm-code", "ide.json");
export const readIDEConfiguration = async (path = defaultPath()): Promise<IDEConfiguration> => { try { return JSON.parse(await readFile(path, "utf8")) as IDEConfiguration; } catch { return {}; } };
export const writeIDEConfiguration = async (configuration: IDEConfiguration, path = defaultPath()): Promise<void> => { await mkdir(dirname(path), { recursive: true, mode: 0o700 }); const temporary = `${path}.${randomUUID()}.tmp`; await writeFile(temporary, `${JSON.stringify(configuration, null, 2)}\n`, { mode: 0o600 }); await chmod(temporary, 0o600); await rename(temporary, path); };
export const resolveIDESelection = async (input: { explicit?: string; userConfigPath?: string; projectRoot?: string; detected?: string[] }): Promise<{ id?: string; source: "explicit" | "user" | "project" | "detected" | "none" }> => { if (input.explicit) return { id: input.explicit, source: "explicit" }; const user = await readIDEConfiguration(input.userConfigPath); if (user.selectedIDE) return { id: user.selectedIDE, source: "user" }; if (input.projectRoot) { try { const project = JSON.parse(await readFile(join(input.projectRoot, ".easy-llm-code.json"), "utf8")) as { preferredIDE?: string }; if (project.preferredIDE) return { id: project.preferredIDE, source: "project" }; } catch {} } return input.detected?.[0] ? { id: input.detected[0], source: "detected" } : { source: "none" }; };
