import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { randomBytes, randomUUID } from "node:crypto";
import { realpath } from "node:fs/promises";
import { relative, resolve, sep } from "node:path";
import type { AddressInfo } from "node:net";
import type { ApprovalRequest, IDECapabilities, IDEProtocolEvent, RuntimeCapabilities, RuntimeTask, TaskCreateInput } from "@easy-llm/code-ide";
import type { ProjectMemory } from "../memory/project-memory.js";
import { createTaskRunner, type TaskRunResult, type TaskRunnerOptions } from "../task/runner.js";
import type { ApprovalDecision } from "../policy/approval.js";
import { SandboxManager } from "../sandbox/core/sandbox-manager.js";
import { LocalProcessSandboxProvider } from "../sandbox/providers/local/local-process-provider.js";
import { createTaskDiff, normalizeRuntimeEvent, workspaceId } from "./protocol.js";
import { IDEIntegrationError } from "./errors.js";

export interface RuntimeServerOptions { root: string; memory: ProjectMemory; host?: string; port?: number; token?: string; expiresInMs?: number; maxEvents?: number; createRunner?: typeof createTaskRunner; runnerOptions?: Partial<Omit<TaskRunnerOptions, "root" | "memory" | "approval">> }
interface TaskSession { task: RuntimeTask; runner: ReturnType<typeof createTaskRunner>; completion: Promise<TaskRunResult>; approval?: ApprovalRequest; resolveApproval?: (decision: ApprovalDecision) => void }
interface StoredEvent { ordinal: number; event: IDEProtocolEvent }
const capabilities: RuntimeCapabilities = { protocolVersion: "1.0", transports: ["local-http"], operations: ["task.create", "task.pause", "task.resume", "task.cancel", "task.approve", "task.reject", "task.open", "task.diff", "task.inspect"], runtimeEvents: true, sandboxInspection: true, diagnostics: true };
const json = (response: ServerResponse, status: number, value: unknown) => { if (status === 204 || value === undefined) { response.writeHead(status, { "cache-control": "no-store" }); response.end(); return; } const body = JSON.stringify(value); response.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(body), "cache-control": "no-store" }); response.end(body); };
const body = async (request: IncomingMessage): Promise<unknown> => { let value = ""; for await (const chunk of request) { value += chunk; if (Buffer.byteLength(value) > 1_000_000) throw new IDEIntegrationError("REQUEST_TOO_LARGE", "1MB limit"); } return value ? JSON.parse(value) : {}; };
export const startRuntimeServer = async (options: RuntimeServerOptions) => {
  const canonicalRoot = await realpath(options.root), token = options.token ?? randomBytes(32).toString("base64url"), sessionId = randomUUID(), expiresAt = Date.now() + (options.expiresInMs ?? 8 * 60 * 60 * 1000), sessions = new Map<string, TaskSession>(), events: StoredEvent[] = [], taskSequences = new Map<string, number>(); let ordinal = 0, activeTaskId = "", negotiated: { identity?: unknown; capabilities?: IDECapabilities } | undefined;
  const pushEvent = (raw: Parameters<typeof normalizeRuntimeEvent>[0], boundTaskId = "") => { const hintedTask = "taskId" in raw ? raw.taskId : ""; if (hintedTask) activeTaskId = hintedTask; const taskId = hintedTask || boundTaskId || activeTaskId, sequence = taskSequences.get(taskId) ?? 0, event = normalizeRuntimeEvent(raw, sequence); event.taskId = taskId; if (!("payload" in raw && "sequence" in raw)) event.id = `ide-event:${taskId}:${sequence}`; taskSequences.set(taskId, sequence + 1); events.push({ ordinal: ordinal++, event }); if (events.length > (options.maxEvents ?? 2_000)) events.splice(0, events.length - (options.maxEvents ?? 2_000)); };
  const authorize = (request: IncomingMessage) => { if (Date.now() >= expiresAt) throw new IDEIntegrationError("SESSION_EXPIRED", sessionId); if (request.headers.authorization !== `Bearer ${token}`) throw new IDEIntegrationError("UNAUTHORIZED", "invalid runtime session credential"); };
  const requireConnection = () => { if (!negotiated) throw new IDEIntegrationError("IDE_NOT_CONNECTED", "call /v1/connect first"); };
  const validateWorkspace = async (workspace: TaskCreateInput["workspace"]) => { const supplied = await realpath(workspace.repositoryRoot), workspacePath = await realpath(workspace.workspacePath); if (supplied !== canonicalRoot || workspacePath !== canonicalRoot || workspace.workspaceId !== workspaceId(canonicalRoot)) throw new IDEIntegrationError("WORKSPACE_SCOPE_VIOLATION", workspace.repositoryRoot); return canonicalRoot; };
  const validateEditorContext = async (context: TaskCreateInput["editorContext"]) => { if (!context) return undefined; const validatePath = async (value: string) => { const path = await realpath(resolve(canonicalRoot, value)); if (path !== canonicalRoot && !path.startsWith(`${canonicalRoot}${sep}`)) throw new IDEIntegrationError("EDITOR_CONTEXT_SCOPE_VIOLATION", value); return relative(canonicalRoot, path).replace(/\\/g, "/"); }; return { ...(context.activeFile ? { activeFile: await validatePath(context.activeFile) } : {}), ...(context.openFiles ? { openFiles: await Promise.all(context.openFiles.slice(0, 100).map(validatePath)) } : {}), ...(context.selection ? { selection: context.selection } : {}), ...(context.cursor ? { cursor: context.cursor } : {}) }; };
  const getSession = (id: string) => { const value = sessions.get(id); if (!value) throw new IDEIntegrationError("TASK_NOT_IN_SESSION", id); return value; };
  const settleTask = async (session: TaskSession, result: TaskRunResult, failureReason?: string) => { if (session.task.state === "cancelling" && result.state === "paused") { const { resumeState: _resumeState, ...prior } = result.checkpoint, checkpoint = { ...prior, state: "cancelled" as const, updatedAt: new Date().toISOString() }; await options.memory.persistTaskCheckpoint(checkpoint); const task = await options.memory.getTask(result.taskId); if (task) await options.memory.upsertTask({ ...task.task, status: "cancelled", completedAt: new Date().toISOString() }); const sandbox = await options.memory.findSandboxForTask(result.taskId); if (sandbox && sandbox.status !== "destroyed") await new SandboxManager({ memory: options.memory, provider: new LocalProcessSandboxProvider() }).finalize(sandbox.id, false); pushEvent({ type: "task.cancelled", taskId: result.taskId }, result.taskId); session.task.state = "cancelled"; session.task.result = { ...result, state: "cancelled", checkpoint }; return; } session.task.state = result.state; session.task.result = failureReason ? { ...result, failureReason } : result; };
  const createTask = async (input: TaskCreateInput): Promise<RuntimeTask> => { await validateWorkspace(input.workspace); if (!input.request?.trim() || !["ask", "plan", "edit", "auto"].includes(input.mode)) throw new IDEIntegrationError("INVALID_TASK", "request and mode are required"); let taskIdResolve!: (id: string) => void; const taskIdPromise = new Promise<string>((resolve) => taskIdResolve = resolve); let session: TaskSession | undefined, queuedApproval: ApprovalRequest | undefined, queuedApprovalResolver: ((decision: ApprovalDecision) => void) | undefined, boundTaskId = "", failureReason: string | undefined;
    const runner = (options.createRunner ?? createTaskRunner)({ ...options.runnerOptions, root: canonicalRoot, memory: options.memory, approval: async ({ proposal }) => { const associatedTaskId = boundTaskId || proposal.taskId, request: ApprovalRequest = { taskId: associatedTaskId, mutationId: proposal.id, files: proposal.files.map((file) => file.path), verificationPlan: proposal.verification.map((step) => step.command), sandboxId: (await options.memory.findSandboxForTask(associatedTaskId))?.id }; const pendingEvent = [...events].reverse().find((item) => item.event.taskId === associatedTaskId && item.event.type === "approval.required"); if (pendingEvent) pendingEvent.event.payload = { ...pendingEvent.event.payload, ...request } as unknown as Record<string, unknown>; if (session) { session.approval = request; session.task.approval = request; } else queuedApproval = request; return new Promise<ApprovalDecision>((resolve) => { if (session) session.resolveApproval = resolve; else queuedApprovalResolver = resolve; }); } });
    runner.subscribe((event) => { if (event.type === "task.started" && "taskId" in event) { boundTaskId = event.taskId; taskIdResolve(event.taskId); } if (event.type === "task.failed" && "reason" in event) failureReason = event.reason; pushEvent(event, boundTaskId); }); const editorContext = await validateEditorContext(input.editorContext), completion = runner.run({ request: input.request, mode: input.mode, ...(editorContext ? { editorContext } : {}) }); const taskId = await taskIdPromise, task: RuntimeTask = { id: taskId, request: input.request, state: "running", createdAt: new Date().toISOString(), approval: queuedApproval }; session = { task, runner, completion, approval: queuedApproval, resolveApproval: queuedApprovalResolver }; sessions.set(taskId, session); await options.memory.addRelationship({ id: `edge:task-workspace:${taskId}`, from: `task:${taskId}`, to: input.workspace.workspaceId, relation: "ASSOCIATED_WORKSPACE", confidence: 1, source: "agent" }); if (input.ide) { await options.memory.addRelationship({ id: `edge:task-ide:${taskId}`, from: `task:${taskId}`, to: `ide:${input.ide.id}`, relation: "RUN_IN_IDE", confidence: 1, source: "agent" }); await options.memory.recordObservation({ id: `ide-session:${taskId}`, type: "decision", taskId, content: { ide: input.ide.id, adapterVersion: input.ide.adapterVersion, capabilities: input.ide.capabilities }, timestamp: new Date().toISOString() }); } void completion.then((result) => settleTask(session!, result, failureReason)).catch((error) => { session!.task.state = "failed"; session!.task.result = { error: (error as Error).message }; }); return task; };
  const server = createServer(async (request, response) => { try { const url = new URL(request.url ?? "/", "http://localhost"); if (url.pathname === "/health" && request.method === "GET") return json(response, 200, { status: "ok", protocolVersion: capabilities.protocolVersion, expiresAt: new Date(expiresAt).toISOString() }); authorize(request);
      if (url.pathname === "/v1/connect" && request.method === "POST") { const input = await body(request) as { identity?: unknown; capabilities?: IDECapabilities }; negotiated = input; return json(response, 200, { sessionId, capabilities: input.capabilities ?? {}, protocolVersion: capabilities.protocolVersion, expiresAt: new Date(expiresAt).toISOString() }); }
      if (url.pathname === "/v1/disconnect" && request.method === "POST") { negotiated = undefined; return json(response, 204, undefined); }
      if (url.pathname === "/v1/capabilities" && request.method === "GET") return json(response, 200, capabilities);
      if (url.pathname === "/v1/events" && request.method === "GET") { requireConnection(); const after = Number(url.searchParams.get("after") ?? -1), selected = events.filter((item) => item.ordinal > after); return json(response, 200, { events: selected.map((item) => item.event), cursor: selected.at(-1)?.ordinal ?? after }); }
      if (url.pathname === "/v1/tasks" && request.method === "GET") { requireConnection(); return json(response, 200, [...sessions.values()].map((item) => item.task)); }
      if (url.pathname === "/v1/tasks" && request.method === "POST") { requireConnection(); return json(response, 202, await createTask(await body(request) as TaskCreateInput)); }
      const match = url.pathname.match(/^\/v1\/tasks\/([^/]+)(?:\/([^/]+))?$/); if (match) { requireConnection(); const taskId = decodeURIComponent(match[1]), action = match[2], session = getSession(taskId);
        if (!action && request.method === "GET") { const stored = await options.memory.getTaskCheckpoint(taskId); if (stored) session.task.state = stored.state; return json(response, 200, session.task); }
        if (action === "pause" && request.method === "POST") { if (session.resolveApproval) { session.resolveApproval("paused"); session.resolveApproval = undefined; session.approval = undefined; session.task.approval = undefined; } else session.runner.cancel(); session.task.state = "pausing"; return json(response, 202, session.task); }
        if (action === "cancel" && request.method === "POST") { if (session.resolveApproval) session.resolveApproval("rejected"); else session.runner.cancel(); session.task.state = "cancelling"; return json(response, 202, session.task); }
        if (action === "resume" && request.method === "POST") { session.completion = session.runner.resume(taskId); session.task.state = "running"; void session.completion.then((result) => settleTask(session, result)); return json(response, 202, session.task); }
        if (["approve", "approve-and-continue", "reject"].includes(action ?? "") && request.method === "POST") { if (!session.resolveApproval) throw new IDEIntegrationError("APPROVAL_NOT_PENDING", taskId); session.resolveApproval(action === "reject" ? "rejected" : "approved"); session.resolveApproval = undefined; session.approval = undefined; session.task.approval = undefined; return json(response, 202, session.task); }
        if (action === "diff" && request.method === "GET") { const proposal = await options.memory.findMutationForPlan((await options.memory.findPlanForTask(taskId))?.id ?? ""); return json(response, 200, createTaskDiff(taskId, proposal?.files ?? [])); }
        if (action === "sandbox" && request.method === "GET") { const sandbox = await options.memory.findSandboxForTask(taskId); if (!sandbox || sandbox.taskId !== taskId) throw new IDEIntegrationError("SANDBOX_NOT_FOUND", taskId); return json(response, 200, await new SandboxManager({ memory: options.memory, provider: new LocalProcessSandboxProvider() }).inspect(sandbox.id)); }
        if (action === "diagnostics" && request.method === "GET") { const runs = await options.memory.getVerificationRuns(taskId), diagnostics = runs.flatMap((run) => run.results.filter((item) => item.status !== "passed").map((item) => { const output = item.stderr || item.stdout || item.classification || "Verification failed", match = output.match(/(?:^|\n)([^:\n]+):(\d+)(?::(\d+))?[:\s]+([^\n]+)/); return { ...(match ? { file: match[1], line: Number(match[2]), ...(match[3] ? { column: Number(match[3]) } : {}), message: match[4] } : { message: output.slice(0, 4_000) }), severity: "error", source: item.command, taskId }; })); return json(response, 200, { diagnostics }); }
      }
      if (url.pathname === "/v1/shutdown" && request.method === "POST") { json(response, 202, { shuttingDown: true }); setImmediate(() => server.close()); return; }
      json(response, 404, { error: "not found" });
    } catch (error) { const status = error instanceof IDEIntegrationError && error.code === "UNAUTHORIZED" ? 401 : error instanceof IDEIntegrationError && ["WORKSPACE_SCOPE_VIOLATION", "TASK_NOT_IN_SESSION", "SANDBOX_NOT_FOUND"].includes(error.code) ? 403 : 400; json(response, status, { error: (error as Error).message }); } });
  await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(options.port ?? 0, options.host ?? "127.0.0.1", () => resolve()); }); const address = server.address() as AddressInfo;
  return { server, token, sessionId, expiresAt: new Date(expiresAt).toISOString(), url: `http://${address.address.includes(":") ? `[${address.address}]` : address.address}:${address.port}`, capabilities, workspace: { workspacePath: canonicalRoot, repositoryRoot: canonicalRoot, workspaceId: workspaceId(canonicalRoot) }, close: () => new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())) };
};
