import assert from "node:assert/strict";
import { readFile, stat } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const website = resolve(import.meta.dirname, ".."), repository = resolve(website, "../.."), read = path => readFile(resolve(website, path), "utf8");
test("homepage communicates one product and one primary installation path", async () => { const html = await read("dist/index.html"); assert.match(html, /Your coding agent that <span>remembers/); assert.match(html, /href="\/install\/"/); assert.match(html, /No account required/); assert.match(html, /Local-first memory/); assert.match(html, /<main>/); assert.match(html, /aria-label="Main navigation"/); });
test("install page supports every public install and IDE path", async () => { const html = await read("dist/install/index.html"); for (const platform of ["mac", "linux", "windows"]) assert.match(html, new RegExp(`data-platform-tab="${platform}"`)); assert.match(html, /install\.sh/); assert.match(html, /install\.ps1/); assert.match(html, /brew install --cask easy-llm-code/); assert.match(html, /npm install -g @easy-llm\/code-agent/); for (const ide of ["cursor", "vscode", "zed"]) assert.match(html, new RegExp(`easy-llm-code://setup\\?ide=${ide}`)); });
test("website publishes the canonical, executable installer sources", async () => { const pairs = [["dist/install.sh", "distribution/install.sh"], ["dist/install.ps1", "distribution/install.ps1"]]; for (const [built, source] of pairs) assert.equal(await read(built), await readFile(resolve(repository, source), "utf8")); assert.ok((await stat(resolve(website, "dist/install.sh"))).size > 500); });
test("client behavior includes platform detection, accessible tabs, and copy feedback", async () => { const script = await read("dist/site.js"), html = await read("dist/install/index.html"); assert.match(script, /navigator\.userAgent/); assert.match(script, /navigator\.clipboard\.writeText/); assert.match(script, /aria-selected/); assert.match(html, /role="tablist"/); assert.match(html, /<noscript>/); });
test("Vercel deployment is artifact-only and preserves installer content types", async () => { const config = JSON.parse(await read(".vercel/output/config.json")); assert.equal(config.version, 3); assert.match(JSON.stringify(config.routes), /install\\\\\.sh/); assert.match(JSON.stringify(config.routes), /text\/plain/); await stat(resolve(website, ".vercel/output/static/index.html")); await assert.rejects(stat(resolve(website, ".vercel/output/static/vercel.json"))); });
