import { createHash, randomUUID } from "node:crypto";
import { dirname, join } from "node:path";
import type { ProjectMemory } from "../../memory/project-memory.js";
import type { SandboxProvider } from "./sandbox-provider.js";
import type { ExecutionResult, FilesystemChange, NetworkObservation, ResourceLimits, Sandbox, SandboxCommand, SandboxCreateInput, SandboxEvent, SandboxHandle, SandboxPolicy, SandboxSnapshot, SandboxStatus } from "./sandbox-types.js";
import { DEFAULT_RESOURCE_LIMITS, DEFAULT_SANDBOX_POLICY, authorizeNetworkHost, authorizeSandboxCommand } from "./sandbox-policy.js";
import { SandboxError } from "./sandbox-errors.js";
import { detectWorkspaceOrigin } from "../workspace/workspace.js";
import { detectSandboxEnvironment } from "../environment/detector.js";
import { createEnvironmentFingerprint } from "../environment/fingerprint.js";
import { classifyFilesystemChanges, scanFilesystem } from "../filesystem/observer.js";
import { createSandboxDiff } from "../workspace/diff.js";

const transitions: Record<SandboxStatus, SandboxStatus[]> = { created: ["preparing", "failed"], preparing: ["ready", "failed"], ready: ["running", "stopping", "failed"], running: ["paused", "stopping", "failed"], paused: ["running", "stopping", "failed"], stopping: ["destroyed", "failed"], destroyed: [], failed: ["preparing", "stopping"] };
const zeroUsage = () => ({ durationMs: 0, cpuMs: 0, peakMemoryBytes: 0, processCount: 0, filesystemChangeCount: 0, outputBytes: 0, networkEventCount: 0 });
export interface SandboxManagerOptions { memory: ProjectMemory; provider: SandboxProvider; policy?: Partial<SandboxPolicy>; limits?: Partial<ResourceLimits>; approveCommand?: (input: { sandbox: Sandbox; command: SandboxCommand; reason: string }) => Promise<boolean> }
export class SandboxManager {
  private readonly handles = new Map<string, SandboxHandle>(); private readonly subscribers = new Set<(event: SandboxEvent) => void>();
  constructor(private readonly options: SandboxManagerOptions) {}
  subscribe(listener: (event: SandboxEvent) => void) { this.subscribers.add(listener); return () => this.subscribers.delete(listener); }
  private async emit(sandbox: Sandbox, type: string, payload: Record<string, unknown> = {}): Promise<SandboxEvent> { const existing = await this.options.memory.getSandboxEvents(sandbox.id), sequence = (existing.at(-1)?.sequence ?? -1) + 1, event = { id: `sandbox-event:${sandbox.id}:${sequence}`, sandboxId: sandbox.id, taskId: sandbox.taskId, timestamp: new Date().toISOString(), type, sequence, payload }; await this.options.memory.persistSandboxEvent(event); for (const listener of this.subscribers) listener(event); return event; }
  private async transition(sandbox: Sandbox, status: SandboxStatus, type = `sandbox.${status}`): Promise<Sandbox> { if (!transitions[sandbox.status].includes(status)) throw new SandboxError("INVALID_SANDBOX_TRANSITION", `${sandbox.status} -> ${status}`); const updated = { ...sandbox, status, startedAt: status === "running" && !sandbox.startedAt ? new Date().toISOString() : sandbox.startedAt, destroyedAt: status === "destroyed" ? new Date().toISOString() : sandbox.destroyedAt }; await this.options.memory.persistSandbox(updated); await this.emit(updated, type, { status }); return updated; }
  private policy(): SandboxPolicy { return { ...DEFAULT_SANDBOX_POLICY, ...this.options.policy, commands: { ...DEFAULT_SANDBOX_POLICY.commands, ...this.options.policy?.commands }, network: { ...DEFAULT_SANDBOX_POLICY.network, ...this.options.policy?.network } }; }
  private limits(): ResourceLimits { return { ...DEFAULT_RESOURCE_LIMITS, ...this.options.limits }; }
  async create(input: { taskId: string; projectId: string; repositoryPath: string }): Promise<Sandbox> { const id = `sandbox:${input.taskId}`, policy = this.policy(), limits = this.limits(), createInput: SandboxCreateInput = { sandboxId: id, ...input, policy, limits }, handle = await this.options.provider.create(createInput), origin = await detectWorkspaceOrigin(input.repositoryPath), now = new Date().toISOString(); this.handles.set(id, handle); const sandbox: Sandbox = { id, taskId: input.taskId, projectId: input.projectId, provider: this.options.provider.name, status: "created", createdAt: now, workspace: { path: handle.workspacePath, origin, retained: true }, policy, limits, resourceUsage: zeroUsage() }; await this.options.memory.persistSandbox(sandbox); await this.emit(sandbox, "sandbox.created", { provider: sandbox.provider, workspace: sandbox.workspace.path }); return sandbox; }
  async prepare(sandboxId: string, metadata: { languages?: string[]; frameworks?: string[] } = {}): Promise<Sandbox> { let sandbox = await this.required(sandboxId); sandbox = await this.transition(sandbox, "preparing", "sandbox.preparing"); const handle = await this.handle(sandbox); try { await this.options.provider.prepare(handle, { sandboxId: sandbox.id, taskId: sandbox.taskId, projectId: sandbox.projectId, repositoryPath: sandbox.workspace.origin.repositoryPath, policy: sandbox.policy, limits: sandbox.limits }); const environment = await detectSandboxEnvironment(handle.workspacePath, metadata.languages, metadata.frameworks); await this.emit(sandbox, "environment.detected", { environment }); const fingerprint = await createEnvironmentFingerprint({ workspace: handle.workspacePath, environment, provider: this.options.provider.name, providerVersion: this.options.provider.version, networkPolicy: sandbox.policy.network, limits: sandbox.limits }); sandbox = { ...sandbox, environment, fingerprint }; await this.options.memory.persistSandboxFingerprint(sandbox.id, fingerprint); await this.emit(sandbox, "environment.fingerprinted", { fingerprint: fingerprint.fingerprint }); await this.options.memory.persistSandbox(sandbox); sandbox = await this.transition(sandbox, "ready", "sandbox.ready"); const snapshot = await this.snapshot(sandbox.id, "sandbox.ready"); sandbox = { ...(await this.required(sandbox.id)), snapshot, workspace: { ...sandbox.workspace, baselineSnapshotId: snapshot.id } }; await this.options.memory.persistSandbox(sandbox); return sandbox; } catch (error) { await this.fail(sandbox, error); throw error; } }
  async start(sandboxId: string): Promise<Sandbox> { return this.transition(await this.required(sandboxId), "running", "sandbox.started"); }
  async pause(sandboxId: string): Promise<Sandbox> { return this.transition(await this.required(sandboxId), "paused", "sandbox.paused"); }
  async resume(sandboxId: string): Promise<Sandbox> { let sandbox = await this.required(sandboxId); if (sandbox.status === "destroyed") throw new SandboxError("SANDBOX_DESTROYED", sandboxId); const handle = await this.handle(sandbox), inspection = await this.options.provider.inspect(handle); if (!inspection.exists) { const snapshot = sandbox.snapshot ?? (await this.options.memory.getSandboxSnapshots(sandboxId)).at(-1); if (!snapshot) throw new SandboxError("SANDBOX_NOT_RECOVERABLE", sandboxId); const replacement = await this.options.provider.create({ sandboxId: sandbox.id, taskId: sandbox.taskId, projectId: sandbox.projectId, repositoryPath: sandbox.workspace.origin.repositoryPath, policy: sandbox.policy, limits: sandbox.limits }); this.handles.set(sandbox.id, replacement); await this.options.provider.prepare(replacement, { sandboxId: sandbox.id, taskId: sandbox.taskId, projectId: sandbox.projectId, repositoryPath: sandbox.workspace.origin.repositoryPath, policy: sandbox.policy, limits: sandbox.limits }); await this.options.provider.restore(replacement, snapshot); sandbox = { ...sandbox, workspace: { ...sandbox.workspace, path: replacement.workspacePath, retained: true }, status: "paused" }; await this.options.memory.persistSandbox(sandbox); }
    if (sandbox.fingerprint) { const current = await createEnvironmentFingerprint({ workspace: (await this.handle(sandbox)).workspacePath, environment: sandbox.environment!, provider: this.options.provider.name, providerVersion: this.options.provider.version, networkPolicy: sandbox.policy.network, limits: sandbox.limits }); const compatible = (value: typeof current) => ({ os: value.os, architecture: value.architecture, runtimeVersions: value.runtimeVersions, packageManagers: value.packageManagers, toolVersions: value.toolVersions, sandboxProvider: value.sandboxProvider, sandboxProviderVersion: value.sandboxProviderVersion, networkPolicy: value.networkPolicy, resourceLimits: value.resourceLimits }); if (JSON.stringify(compatible(current)) !== JSON.stringify(compatible(sandbox.fingerprint))) throw new SandboxError("SANDBOX_ENVIRONMENT_MISMATCH", sandboxId); }
    return sandbox.status === "paused" ? this.transition(sandbox, "running", "sandbox.resumed") : sandbox;
  }
  async execute(sandboxId: string, command: SandboxCommand): Promise<ExecutionResult> { let sandbox = await this.required(sandboxId); if (sandbox.status !== "running") throw new SandboxError(sandbox.status === "destroyed" ? "SANDBOX_DESTROYED" : "SANDBOX_NOT_RUNNING", sandbox.status); const authorization = authorizeSandboxCommand(command, sandbox.policy); let approved = authorization.decision === "allowed"; if (authorization.decision === "requiresApproval" && this.options.approveCommand) approved = await this.options.approveCommand({ sandbox, command, reason: authorization.reason });
    const network: NetworkObservation[] = []; for (const host of command.networkHosts ?? []) { const allowed = authorizeNetworkHost(host, sandbox.policy.network), observation = { id: `network:${sandbox.id}:${createHash("sha256").update(host).digest("hex").slice(0, 12)}`, sandboxId: sandbox.id, taskId: sandbox.taskId, host, direction: "outbound" as const, decision: allowed ? "allowed" as const : "blocked" as const, timestamp: new Date().toISOString() }; network.push(observation); await this.options.memory.persistNetworkObservation(observation); await this.emit(sandbox, "network.requested", { host }); await this.emit(sandbox, allowed ? "network.allowed" : "network.blocked", { host }); if (!allowed) approved = false; }
    await this.emit(sandbox, "command.started", { executable: command.executable, args: command.args, cwd: command.cwd ?? "." }); if (!approved) { const result: ExecutionResult = { id: `command:${sandbox.id}:${randomUUID()}`, sandboxId: sandbox.id, taskId: sandbox.taskId, command, stdout: "", stderr: authorization.reason, durationMs: 0, resourceUsage: { ...zeroUsage(), networkEventCount: network.length }, processes: [], filesystemChanges: [], network, status: "blocked", failureReason: authorization.decision === "requiresApproval" ? "permission" : network.some((item) => item.decision === "blocked") ? "network_blocked" : "permission" }; await this.options.memory.persistSandboxCommand(result); await this.emit(sandbox, "command.failed", { status: result.status, reason: result.failureReason }); return result; }
    const result = await this.options.provider.execute(await this.handle(sandbox), command); result.network = network; result.resourceUsage.networkEventCount = network.length; await this.options.memory.persistSandboxCommand(result); for (const process of result.processes) { await this.options.memory.persistProcessObservation(process); await this.emit(sandbox, "process.started", { pid: process.pid, parentPid: process.parentPid, executable: process.executable, startedAt: process.startedAt }); if (process.exitedAt) await this.emit(sandbox, "process.exited", { pid: process.pid, parentPid: process.parentPid, executable: process.executable, exitCode: process.exitCode, signal: process.signal, exitedAt: process.exitedAt }); } for (const change of result.filesystemChanges) { await this.options.memory.persistFilesystemChange(change); const payload = { path: change.path, oldPath: change.oldPath, operation: change.operation, beforeHash: change.beforeHash, afterHash: change.afterHash }; await this.emit(sandbox, "filesystem.change.detected", payload); await this.emit(sandbox, `filesystem.file.${change.operation}`, payload); }
    if (result.stdout) await this.emit(sandbox, "command.stdout", { output: result.stdout.slice(0, 4_000), truncated: result.stdout.length > 4_000 }); if (result.stderr) await this.emit(sandbox, "command.stderr", { output: result.stderr.slice(0, 4_000), truncated: result.stderr.length > 4_000 }); if (result.status === "resource_exceeded" || result.status === "timed_out") await this.emit(sandbox, result.status === "timed_out" ? "process.limit.exceeded" : "resource.exceeded", { reason: result.failureReason });
    const prior = sandbox.resourceUsage, usage = { durationMs: prior.durationMs + result.resourceUsage.durationMs, cpuMs: prior.cpuMs + result.resourceUsage.cpuMs, peakMemoryBytes: Math.max(prior.peakMemoryBytes, result.resourceUsage.peakMemoryBytes), processCount: prior.processCount + result.resourceUsage.processCount, filesystemChangeCount: prior.filesystemChangeCount + result.resourceUsage.filesystemChangeCount, outputBytes: prior.outputBytes + result.resourceUsage.outputBytes, networkEventCount: prior.networkEventCount + result.resourceUsage.networkEventCount }; sandbox = { ...sandbox, resourceUsage: usage }; await this.options.memory.persistSandboxResourceUsage(sandbox.id, usage); await this.options.memory.persistSandbox(sandbox); await this.emit(sandbox, result.status === "completed" ? "command.completed" : "command.failed", { commandId: result.id, exitCode: result.exitCode, signal: result.signal, durationMs: result.durationMs, status: result.status, reason: result.failureReason }); return result;
  }
  async snapshot(sandboxId: string, label: string): Promise<SandboxSnapshot> { const sandbox = await this.required(sandboxId); if (sandbox.status === "destroyed") throw new SandboxError("SANDBOX_DESTROYED", sandboxId); const prior = await this.options.memory.getSandboxSnapshots(sandboxId), id = `snapshot:${sandboxId}:${prior.length}`, snapshot = await this.options.provider.snapshot(await this.handle(sandbox), { id, label, environmentFingerprint: sandbox.fingerprint?.fingerprint ?? "pending", origin: sandbox.workspace.origin, policy: sandbox.policy, limits: sandbox.limits }); await this.options.memory.persistSandboxSnapshot(snapshot); await this.emit(sandbox, "snapshot.created", { snapshotId: id, label, workspaceHash: snapshot.workspaceHash }); await this.options.memory.persistSandbox({ ...sandbox, snapshot }); return snapshot; }
  async restore(sandboxId: string, snapshotId: string): Promise<void> { const sandbox = await this.required(sandboxId), snapshot = await this.options.memory.getSandboxSnapshot(snapshotId); if (!snapshot || snapshot.sandboxId !== sandboxId || snapshot.taskId !== sandbox.taskId) throw new SandboxError("SANDBOX_SNAPSHOT_SCOPE", snapshotId); try { await this.options.provider.restore(await this.handle(sandbox), snapshot); await this.emit(sandbox, "snapshot.restored", { snapshotId }); } catch (error) { await this.emit(sandbox, "snapshot.failed", { snapshotId, error: (error as Error).message }); await this.fail(sandbox, error); throw error; } }
  async observeChanges(sandboxId: string, snapshot: SandboxSnapshot): Promise<FilesystemChange[]> { const sandbox = await this.required(sandboxId); if (snapshot.sandboxId !== sandboxId) throw new SandboxError("SANDBOX_SNAPSHOT_SCOPE", snapshot.id); const baseline = snapshot.providerData.path; if (typeof baseline !== "string") throw new SandboxError("SANDBOX_SNAPSHOT_INVALID", snapshot.id); const changes = classifyFilesystemChanges(await scanFilesystem(baseline), await scanFilesystem((await this.handle(sandbox)).workspacePath), { sandboxId, taskId: sandbox.taskId }); for (const change of changes) { await this.options.memory.persistFilesystemChange(change); await this.emit(sandbox, "filesystem.changed", { path: change.path, operation: change.operation, beforeHash: change.beforeHash, afterHash: change.afterHash }); } return changes;
  }
  async diff(sandboxId: string): Promise<string> { const sandbox = await this.required(sandboxId); if (sandbox.status === "destroyed") return sandbox.diff ?? ""; const baseline = sandbox.snapshot?.providerData.path; if (typeof baseline !== "string") return sandbox.diff ?? ""; return createSandboxDiff(baseline, (await this.handle(sandbox)).workspacePath, sandbox.id, sandbox.taskId); }
  async finalize(sandboxId: string, success: boolean): Promise<Sandbox> { let sandbox = await this.required(sandboxId); const diff = await this.diff(sandboxId); sandbox = { ...sandbox, diff }; await this.options.memory.persistSandbox(sandbox); const destroy = sandbox.policy.retention === "destroy" || (sandbox.policy.retention === "retain-on-failure" && success); if (destroy) return this.destroy(sandboxId); if (sandbox.status === "running") sandbox = await this.pause(sandboxId); return sandbox;
  }
  async destroy(sandboxId: string): Promise<Sandbox> { let sandbox = await this.required(sandboxId); if (sandbox.status === "destroyed") return sandbox; if (sandbox.status !== "stopping") sandbox = await this.transition(sandbox, "stopping", "sandbox.stopping"); await this.options.provider.destroy(await this.handle(sandbox)); sandbox = { ...sandbox, workspace: { ...sandbox.workspace, retained: false } }; await this.options.memory.persistSandbox(sandbox); this.handles.delete(sandbox.id); return this.transition(sandbox, "destroyed", "sandbox.destroyed"); }
  async inspect(sandboxId: string) { const sandbox = await this.required(sandboxId); return { sandbox, commands: await this.options.memory.getSandboxCommands(sandboxId), processes: await this.options.memory.getProcessObservations(sandboxId), filesystemChanges: await this.options.memory.getFilesystemChanges(sandboxId), network: await this.options.memory.getNetworkObservations(sandboxId), snapshots: await this.options.memory.getSandboxSnapshots(sandboxId), events: await this.options.memory.getSandboxEvents(sandboxId) }; }
  workspacePath(sandboxId: string): Promise<string> { return this.handleById(sandboxId).then((handle) => handle.workspacePath); }
  private async required(id: string): Promise<Sandbox> { const sandbox = await this.options.memory.getSandbox(id); if (!sandbox) throw new SandboxError("SANDBOX_NOT_FOUND", id); return sandbox; }
  private async handleById(id: string): Promise<SandboxHandle> { return this.handle(await this.required(id)); }
  private async handle(sandbox: Sandbox): Promise<SandboxHandle> { const cached = this.handles.get(sandbox.id); if (cached) return cached; const root = dirname(sandbox.workspace.path), handle = { id: sandbox.id, taskId: sandbox.taskId, projectId: sandbox.projectId, repositoryPath: sandbox.workspace.origin.repositoryPath, workspacePath: sandbox.workspace.path, snapshotRoot: join(root, "snapshots"), provider: sandbox.provider, policy: sandbox.policy, limits: sandbox.limits }; this.handles.set(sandbox.id, handle); return handle; }
  private async fail(sandbox: Sandbox, error: unknown): Promise<void> { const failed = { ...sandbox, status: "failed" as const, failureReason: (error as Error).message }; await this.options.memory.persistSandbox(failed); await this.emit(failed, "sandbox.failed", { error: failed.failureReason }); }
}
