export type SandboxStatus = "created" | "preparing" | "ready" | "running" | "paused" | "stopping" | "destroyed" | "failed";
export type NetworkMode = "none" | "allowlist" | "full";
export interface NetworkPolicy { mode: NetworkMode; hosts: string[] }
export interface ResourceLimits { maxCpuMs: number; maxMemoryBytes: number; maxWallTimeMs: number; maxOutputBytes: number; maxProcesses: number; maxFilesystemChanges: number }
export interface CommandPolicy { allowedExecutables: string[]; blockedExecutables: string[]; requireApprovalExecutables: string[] }
export interface SandboxPolicy { commands: CommandPolicy; network: NetworkPolicy; retention: "destroy" | "retain" | "retain-on-failure" }
export interface WorkspaceOrigin { repositoryPath: string; gitHead?: string; dirtyState: boolean; trackedChangesHash: string; untrackedFilesHash: string; ignoredFilesHash: string; capturedAt: string }
export interface SandboxEnvironment { os: string; architecture: string; cpuCount: number; memoryBytes: number; runtimeVersions: Record<string, string>; packageManagers: Record<string, string>; tools: Record<string, string>; languages: string[]; frameworks: string[] }
export interface EnvironmentFingerprint { os: string; architecture: string; runtimeVersions: Record<string, string>; packageManagers: Record<string, string>; toolVersions: Record<string, string>; lockfileHashes: Record<string, string>; dependencyHashes: Record<string, string>; repositoryHash: string; sandboxProvider: string; sandboxProviderVersion: string; networkPolicy: NetworkPolicy; resourceLimits: ResourceLimits; fingerprint: string }
export interface ResourceUsage { durationMs: number; cpuMs: number; peakMemoryBytes: number; processCount: number; filesystemChangeCount: number; outputBytes: number; networkEventCount: number }
export interface SandboxWorkspace { path: string; origin: WorkspaceOrigin; baselineSnapshotId?: string; retained: boolean }
export interface Sandbox { id: string; taskId: string; projectId: string; provider: string; status: SandboxStatus; createdAt: string; startedAt?: string; destroyedAt?: string; workspace: SandboxWorkspace; environment?: SandboxEnvironment; fingerprint?: EnvironmentFingerprint; policy: SandboxPolicy; limits: ResourceLimits; snapshot?: SandboxSnapshot; resourceUsage: ResourceUsage; diff?: string; failureReason?: string }
export interface SandboxCommand { executable: string; args: string[]; cwd?: string; environment?: Record<string, string>; timeoutMs?: number; stdin?: string; limits?: Partial<ResourceLimits>; networkHosts?: string[] }
export interface ProcessObservation { id: string; sandboxId: string; taskId: string; pid: number; parentPid?: number; executable: string; args: string[]; startedAt: string; exitedAt?: string; exitCode?: number; signal?: string; durationMs?: number }
export interface FilesystemChange { id: string; sandboxId: string; taskId: string; path: string; operation: "created" | "modified" | "deleted" | "renamed"; beforeHash?: string; afterHash?: string; sizeBefore?: number; sizeAfter?: number; timestamp: string; oldPath?: string }
export interface NetworkObservation { id: string; sandboxId: string; taskId: string; host: string; port?: number; protocol?: string; direction: "outbound" | "inbound"; decision: "allowed" | "blocked"; timestamp: string }
export interface ExecutionResult { id: string; sandboxId: string; taskId: string; command: SandboxCommand; exitCode?: number; signal?: string; stdout: string; stderr: string; durationMs: number; resourceUsage: ResourceUsage; processes: ProcessObservation[]; filesystemChanges: FilesystemChange[]; network: NetworkObservation[]; status: "completed" | "failed" | "timed_out" | "blocked" | "resource_exceeded"; failureReason?: string }
export interface SandboxSnapshot { id: string; sandboxId: string; taskId: string; label: string; createdAt: string; workspaceHash: string; environmentFingerprint: string; origin: WorkspaceOrigin; policy: SandboxPolicy; limits: ResourceLimits; providerData: Record<string, unknown> }
export interface SandboxInspection { sandbox: Sandbox; exists: boolean; recoverable: boolean; processes: ProcessObservation[]; filesystemChanges: FilesystemChange[] }
export interface SandboxEvent { id: string; sandboxId: string; taskId: string; timestamp: string; type: string; sequence: number; payload: Record<string, unknown> }
export interface SandboxCreateInput { sandboxId: string; taskId: string; projectId: string; repositoryPath: string; policy: SandboxPolicy; limits: ResourceLimits }
export interface SandboxHandle { id: string; taskId: string; projectId: string; repositoryPath: string; workspacePath: string; snapshotRoot: string; provider: string; policy: SandboxPolicy; limits: ResourceLimits }
